apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: external-secrets
  name: external-secrets
spec:
  targetNamespace: external-secrets
  createNamespace: true
  version: v0.10.6
  chart: external-secrets/external-secrets
  repo: https://charts.external-secrets.io
  valuesContent: |-
    metrics:
      service:
        enabled: true

